name: DocRunner

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: write

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run DocRunner
        uses: eshaanag/docrunner@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
